### ISSUE TITLE
Getting weird error on build stage

### ISSUE THREAD

**Issue by nduartech** [QwikDev/astro#129]
App runs fine in dev mode, but when I build I get this error:
Cannot find module '.../dist/server/manifest_Cvy4s1NH.mjs' imported from /node_modules/astro/dist/core/build/pipeline.js

Stack trace:
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at defaultResolve (node:internal/modules/esm/resolve:1119:11)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:474:34)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
    at generatePages (/node_modules/astro/dist/core/build/generate.js:59:36)
    at AstroBuilder.build /node_modules/astro/dist/core/build/index.js:133:11)
    at async build (/node_modules/astro/dist/core/build/index.js:45:3)
    at async runCommand (/node_modules/astro/dist/cli/index.js:140:7)

Any ideas? Am I doing something wrong?

**Comment by nduartech** [comment]
Ok so I just tested trying to build from a blank slate project, generated from 
- yarn create @qwikdev/astro
and got the error again without any additions to the project... I just really hope I'm not missing anything obvious

**Comment by thejackshelton** [comment]
@nduartech 

https://github.com/QwikDev/astro/issues/128

this is the issue. fix is to install Qwik 1.5.6 for the time being.

Closing as duplicate

**Comment by nduartech** [comment]
Hey so I did try that, didn’t work for me, not sure if it is the same issue… :(

**Comment by nduartech** [comment]
{
  "name": "host",
  "type": "module",
  "private": true,
  "scripts": {
    "astro": "astro",
    "sync": "astro sync",
    "build": "yarn fix && astro build",
    "check": "yarn check.fmt && yarn check.lint && astro check",
    "check.fmt": "prettier --check .",
    "check.lint": "eslint \"**/*.{js,jsx,ts,tsx,astro}\"",
    "dev": "astro dev",
    "fix": "yarn lint && yarn fmt",
    "fmt": "prettier --write .",
    "lint": "eslint --fix \"**/*.{js,jsx,ts,tsx,astro}\"",
    "lint.dry-run": "eslint --fix-dry-run \"**/*.{js,jsx,ts,tsx,astro}\"",
    "preview": "yarn build && yarn serve",
    "prod": "yarn check && astro build",
    "serve": "node ./dist/server/entry.mjs",
    "start": "astro dev --open"
  },
  "dependencies": {
    "@astrojs/check": "^0.7.0",
    "@astrojs/node": "^8.3.0",
    "@astrojs/solid-js": "^4.3.0",
    "@astrojs/svelte": "^5.5.0",
    "@astrojs/tailwind": "^5.1.0",
    "@builder.io/qwik": "^1.5.6",
    "@qwikdev/astro": "^0.5.15",
    "astro": "^4.10.2",
    "solid-js": "^1.8.17",
    "svelte": "^4.2.18",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.4.5"
  },
  "devDependencies": {
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.14.2",
    "@typescript-eslint/eslint-plugin": "^7.13.0",
    "@typescript-eslint/parser": "^7.13.0",
    "eslint": "^8.57.0",
    "eslint-plugin-astro": "^0.34.0",
    "eslint-plugin-qwik": "^1.5.7",
    "prettier": "^3.3.2",
    "prettier-plugin-astro": "^0.14.0"
  }
}

**Comment by thejackshelton** [comment]
> at finalizeResolution (node:internal/modules/esm/resolve:260:11)
> at defaultResolve (node:internal/modules/esm/resolve:1119:11)
> at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
> at ModuleLoader.import (node:internal/modules/esm/loader:474:34)
> at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
> at generatePages (/node_modules/astro/dist/core/build/generate.js:59:36)
> at AstroBuilder.build /node_modules/astro/dist/core/build/index.js:133:11)
> at async build (/node_modules/astro/dist/core/build/index.js:45:3)
> at async runCommand (/node_modules/astro/dist/cli/index.js:140:7)

You need to remove the `^`. 

So:

```
"@builder.io/qwik": "1.5.6",
```

rather than:

```
"@builder.io/qwik": "^1.5.6",
```

**Comment by nduartech** [comment]
Will try that asap, tysm
