### ISSUE TITLE
Error building content collection with bun

### ISSUE THREAD

**Issue by nduartech** [QwikDev/astro#151]
```
 generating static routes 
01:58:13 ▶ src/pages/blog.astro
  astro:build Generating: /blog +943ms
01:58:13   └─ /blog/index.html  astro:build Generating: /blog +1ms
Missing client manifest, loading symbols in the client might 404. Please ensure the client build has run and generated the manifest for the server build.
Missing client manifest, loading symbols in the client might 404. Please ensure the client build has run and generated the manifest for the server build.
serializeQRL: Cannot resolve symbol s_IDRPwPZ2wZ8 in null undefined
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_IDRPwPZ2wZ8 Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:36:52)
    at serializeQRL (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3362:11)
    at mapJoin (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3099:16)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:819:52)
    at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:631:19)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:917:22)
    at reduce (:1:11)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:836:21)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:586:16)
    at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:584:29)
    at processTicksAndRejections (:12:39)
serializeQRL: Cannot resolve symbol s_ArvH2YmMldY in null undefined
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_ArvH2YmMldY Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:36:52)
    at serializeQRL (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3362:11)
    at mapJoin (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3099:16)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:819:52)
    at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:631:19)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:917:22)
    at reduce (:1:11)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:836:21)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:586:16)
    at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:584:29)
    at processTicksAndRejections (:12:39)
Error in renderToStaticMarkup function of @qwikdev/astro:  31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                        ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:36:52)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3114:49)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:2671:10)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:29:9
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4443:8)

Error in renderToStaticMarkup function of @qwikdev/astro:  31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                        ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:36:52)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3114:49)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:2671:10)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:29:9
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:4443:8)

  astro:telemetry {
  astro:telemetry   context: {
  astro:telemetry     isGit: false,
  astro:telemetry     anonymousProjectId: 'f659c86e7a5e8c43664d435cae4348da6a745c83461c7f54271d07a67afffc40',
  astro:telemetry     packageManager: 'bun',
  astro:telemetry     packageManagerVersion: '1.1.20',
  astro:telemetry     anonymousId: 'a09e64f351c0990cd7b23f8360dc11d8b21297c2eda45735f03a17f90a796042',
  astro:telemetry     anonymousSessionId: '11569fdcde3e60f0c52522ce3211d7b46c2fda4045d511462fddb5da0514bd0e'
  astro:telemetry   },
  astro:telemetry   meta: {
  astro:telemetry     nodeVersion: '22.3.0',
  astro:telemetry     viteVersion: '5.3.5',
  astro:telemetry     astroVersion: '4.13.0',
  astro:telemetry     systemPlatform: 'linux',
  astro:telemetry     isDocker: false,
  astro:telemetry     isTTY: true,
  astro:telemetry     isWSL: false,
  astro:telemetry     isCI: false,
  astro:telemetry     ciName: null
  astro:telemetry   }
  astro:telemetry } +1s
  astro:telemetry [
  astro:telemetry   {
  astro:telemetry     "eventName": "ASTRO_CLI_ERROR",
  astro:telemetry     "payload": {
  astro:telemetry       "name": "Error",
  astro:telemetry       "cliCommand": "build",
  astro:telemetry       "isFatal": true,
  astro:telemetry       "anonymousMessageHint": "Code"
  astro:telemetry     }
  astro:telemetry   }
  astro:telemetry ] +0ms
Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
  Stack trace:
    at createAndLogError (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:36:52)
    at mapJoin (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:3099:16)
    at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:631:19)
    at reduce (:1:11)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/packages/host/dist/chunks/server_CXmCj7z1.mjs:586:16)
    at processTicksAndRejections (:12:39)
```

Any ideas?

**Comment by siguici** [comment]
Hey @nduartech.
Can you give more details on the steps to reproduce this bug?

I just tried and it works perfectly for me:
1. `bun create @qwikdev/astro qwik-astro-app node --yes`
2. `bun run build`

Result:
```bash
$ bun run fix && astro build
$ bun run lint && bun run format
$ biome check --apply-unsafe .
internalError/fs  DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ The argument --apply-unsafe is deprecated, it will be removed in the next major release. Use --write --unsafe instead.
  

Checked 12 files in 42ms. No fixes applied.
$ biome format --write .
Formatted 10 files in 18ms. No fixes applied.
18:41:16 [WARN] [config] The feature "astro:env getSecret" is experimental and subject to change (used by @astrojs/node).
18:41:17 [types] Generated 459ms
18:41:17 [@qwikdev/astro] astro:build:start
vite v5.3.5 building for production...
✓ 7 modules transformed.
18:41:22 [build] Waiting for integration "@qwikdev/astro", hook "astro:build:start"...
dist/build/q-bundle-graph-x241h1.json   0.08 kB │ gzip:  0.07 kB
dist/q-manifest.json                    2.41 kB │ gzip:  0.86 kB
dist/qwik-prefetch-service-worker.js    3.66 kB
dist/build/q-wEhaJV_j.css               0.15 kB │ gzip:  0.14 kB
dist/build/q-CaYuVtbJ.js                0.06 kB │ gzip:  0.07 kB
dist/build/q-DxtZThm8.js                0.11 kB │ gzip:  0.12 kB
dist/build/q-DFZHp3Q_.js                0.46 kB │ gzip:  0.33 kB
dist/build/q-UyPL-ORJ.js               60.98 kB │ gzip: 22.41 kB
✓ built in 5.65s
18:41:23 [build] output: "server"
18:41:23 [build] directory: /labs/qwik-astro-app/dist/
18:41:23 [build] adapter: @astrojs/node
18:41:23 [build] Collecting build info...
18:41:23 [build] ✓ Completed in 7.25s.
18:41:23 [build] Building server entrypoints...
18:41:37 [vite] ✓ built in 14.54s
18:41:37 [build] ✓ Completed in 14.64s.
18:41:38 
 finalizing server assets 

18:41:38 [build] Rearranging server assets...
18:41:38 [build] Server built in 22.13s
18:41:38 [build] Complete!
```

**Comment by nduartech** [comment]
So I have output set to 'static' is astro config. When I run bunx --bun astro build --verbose it specifically gets stuck while generating content collections, where I get the above error. The site runs fine in dev mode, just fails in build step.

**pages/blog.astro:**
---
import BlogLayout from '../layouts/BlogLayout.astro'
import { getCollection } from 'astro:content'
import BlogSubLayout from '../layouts/BlogSubLayout.astro'
const blogEntries = await getCollection('blog')
---
<script>
    import {navigate} from "astro:transitions/client";
    import {prefetch} from 'astro:prefetch';

    window.addEventListener('navigate', (event) => {
        prefetch(event.detail);
        setTimeout(navigate(event.detail), 300);
    });
</script>
<BlogLayout title="Technical Blog" navProps={[
    {
        icon: '<svg class="nav w-7 h-7" stroke-width="0.8" fill="none" xmlns="http://www.w3.org/2000/svg" color="#ddf2ff" viewBox="2.55 3.23 18.9 18.22"><path d="M9 21H7C4.79086 21 3 19.2091 3 17V10.7076C3 9.30887 3.73061 8.01175 4.92679 7.28679L9.92679 4.25649C11.2011 3.48421 12.7989 3.48421 14.0732 4.25649L19.0732 7.28679C20.2694 8.01175 21 9.30887 21 10.7076V17C21 19.2091 19.2091 21 17 21H15M9 21V17C9 15.3431 10.3431 14 12 14V14C13.6569 14 15 15.3431 15 17V21M9 21H15" stroke="#ddf2ff" stroke-width="0.8" stroke-linecap="round" stroke-linejoin="round" class="svg-elem-5"></path></svg>',
        label: "Home",
        path: "/"
    }, {
        icon: '<svg viewBox="0 0 24 24" class="nav w-7 h-7" stroke-width="0.9" fill="none" xmlns="http://www.w3.org/2000/svg" color="#ffffff"><path d="M6.81815 22L6.81819 19.143C6.66235 17.592 5.63284 16.4165 4.68213 15M14.4545 22L14.4545 20.2858C19.3636 20.2858 18.8182 14.5717 18.8182 14.5717C18.8182 14.5717 21 14.5717 21 12.286L18.8182 8.8576C18.8182 4.28632 15.1094 2.04169 11.1818 2.00068C8.98139 1.97771 7.22477 2.53124 5.91201 3.5" stroke="#ffffff" stroke-width="0.9" stroke-linecap="round" stroke-linejoin="round" class="svg-elem-10"></path><path d="M13 7L15 9.5L13 12" stroke="#ffffff" stroke-width="0.9" stroke-linecap="round" stroke-linejoin="round" class="svg-elem-20"></path><path d="M5 7L3 9.5L5 12" stroke="#ffffff" stroke-width="0.9" stroke-linecap="round" stroke-linejoin="round" class="svg-elem-30"></path><path d="M10 6L8 13" stroke="#ffffff" stroke-width="0.9" stroke-linecap="round" stroke-linejoin="round" class="svg-elem-40"></path></svg>',
        label: "Work",
        path: "/software-engineer"
    }, {
        icon: '<svg class="nav w-7 h-7" stroke-width="0.9" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#ffffff" width="24" height="24"><path d="M22 8.86222C22 10.4087 21.4062 11.8941 20.3458 12.9929C17.9049 15.523 15.5374 18.1613 13.0053 20.5997C12.4249 21.1505 11.5042 21.1304 10.9488 20.5547L3.65376 12.9929C1.44875 10.7072 1.44875 7.01723 3.65376 4.73157C5.88044 2.42345 9.50794 2.42345 11.7346 4.73157L11.9998 5.00642L12.2648 4.73173C13.3324 3.6245 14.7864 3 16.3053 3C17.8242 3 19.2781 3.62444 20.3458 4.73157C21.4063 5.83045 22 7.31577 22 8.86222Z" stroke="#ffffff" stroke-width="0.9" stroke-linejoin="round" class="svg-elem-12"></path></svg>',
        label: "Interests",
        path: "/interests"
    }
]}>
    <BlogSubLayout>
                <div>
                    <h1 class="text-regal-blue-50 text-2xl pb-5 font-medium">Posts</h1>
                    <ul class="space-y-4">
                        {blogEntries.map(blogPostEntry => (
                                <li key={blogPostEntry.data.title} class="text-regal-blue-50">
                                    <a class="text-regal-blue-50 text-md font-semibold"
                                       href={`/blog/${blogPostEntry.slug}`}>{blogPostEntry.data.title} <span
                                            class="text-xs font-medium">- {blogPostEntry.data.description}
                                        | Published {blogPostEntry.data.pubDate.toLocaleDateString("Eastern")}
                                        ~ Tags: [{blogPostEntry.data.tags.map(t => t.toLowerCase()).join(", ")}]</span></a>
                                </li>
                        ))}
                    </ul>
                </div>
    </BlogSubLayout>
</BlogLayout>

**pages/blog/[...slug].astro :**
---
import { getCollection } from 'astro:content'
import PostLayout from '../../layouts/PostLayout.astro'

export async function getStaticPaths() {
  const blogEntries = await getCollection('blog')
  return blogEntries.map((entry) => ({
    params: { slug: entry.slug },
    props: { entry },
  }))
}

const { entry } = Astro.props
const { Content } = await entry.render()
---
<PostLayout title={entry.data.title}>
    <div class="space-y-2 pt-10">
    <span class="text-regal-blue-50 text-md lg:text:lg"><span class="text-regal-blue-50 text-xl lg:text-2xl">{entry.data.title} | </span> {entry.data.description}</span>
    <div class="text-regal-blue-50 text-xs lg:text:xs">Published: {entry.data.pubDate.toLocaleDateString('Eastern')}</div>
    <div class="text-regal-blue-50 text-xs lg:text:xs">Tags: [{entry.data.tags.map(t=>t.toLowerCase()).join(", ")}]</div>
    <div class="text-regal-blue-50"><Content /></div>
    </div>
</PostLayout>


**content/config.ts:**
import { z, defineCollection } from 'astro:content'

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    pubDate: z.date(),
    description: z.string(),
    // image: z.object({
    //     url: z.string(),
    //     alt: z.string()
    // }),
    tags: z.array(z.string()),
  }),
})

export const collections = {
  blog: blogCollection,
}

With md and mdx files in content/blog

**Comment by thejackshelton** [comment]
@nduartech we would need a minimal reproduction of the problem in bun to be able to debug this further. A stackblitz or link to a link on github with the least amount of code necessary to reproduce the problem.

**Comment by nduartech** [comment]
Totally, will send a repo link if that works. Incidentally, the build completes successfully for server output, only failing for static

**Comment by nduartech** [comment]
Hope this helps: https://github.com/nduartech/bunsonalWebsite
Thanks again!

**Comment by thejackshelton** [comment]
> Hope this helps: https://github.com/nduartech/bunsonalWebsite, I think the error can be seen in the Github Action as well: https://github.com/nduartech/bunsonalWebsite/actions/runs/10224680334/job/28292738394 Thanks again!

Hey @nduartech! Can you create a minimal reproduction? I can see in the code that three separate frameworks and a monorepo on top of bun is being used, which makes it much more difficult to narrow down the source of the issue.

**Comment by thejackshelton** [comment]
Are you running into a similar issue here?

https://discord.com/channels/842438759945601056/1150941080355881080/1269313632324423793

where dev mode works, but there is a serialize QRL issue on build specifically when you use a qwik component library?

**Comment by nduartech** [comment]
Ok so I trimmed even more out, still seeing the issue. If you run bunx --bun astro dev and go to localhost:4321/blog it should work. But when you run bunx --bun astro build it fails.  https://github.com/nduartech/bunsonalWebsite 

It does look like it might be the same serialize QRL issue though, not sure...
```
13:33:24 [types] Generated 121ms
13:33:24 [@qwikdev/astro] astro:build:start
vite v5.3.5 building for production...
✓ 19 modules transformed.
dist/build/q-bundle-graph-euafrb.json   0.32 kB │ gzip:  0.21 kB
dist/qwik-prefetch-service-worker.js    3.66 kB
dist/q-manifest.json                    8.96 kB │ gzip:  1.56 kB
dist/build/q-Dz4-v2Rv.js                0.14 kB │ gzip:  0.14 kB
dist/build/q-CK9Sa9Tq.js                0.14 kB │ gzip:  0.14 kB
dist/build/q-C9xGGfPu.js                0.14 kB │ gzip:  0.14 kB
dist/build/q-G7DyVQW3.js                0.15 kB │ gzip:  0.13 kB
dist/build/q-WxtPe1uB.js                0.15 kB │ gzip:  0.13 kB
dist/build/q-CWZxFTIS.js                0.16 kB │ gzip:  0.14 kB
dist/build/q-BIh64hxO.js                0.29 kB │ gzip:  0.20 kB
dist/build/q-Dpno82GK.js                0.38 kB │ gzip:  0.24 kB
dist/build/q-FOsKetIp.js                0.46 kB │ gzip:  0.32 kB
dist/build/q-Cp0PKzzA.js                0.48 kB │ gzip:  0.36 kB
dist/build/q-ZckViiSO.js                0.58 kB │ gzip:  0.26 kB
dist/build/q-CfbFv1E3.js                0.83 kB │ gzip:  0.33 kB
dist/build/q-CjXa90fl.js                2.53 kB │ gzip:  0.72 kB
dist/build/q-ek8uuHcR.js                2.66 kB │ gzip:  1.09 kB
dist/build/q-CA6nPqmb.js                3.72 kB │ gzip:  0.62 kB
dist/build/q-BWCb9iO4.js               62.25 kB │ gzip: 22.81 kB
✓ built in 274ms
13:33:24 [build] output: "static"
13:33:24 [build] directory: /home/nathan/Projects/bunsonalWebsite/dist/
13:33:24 [build] Collecting build info...
13:33:24 [build] ✓ Completed in 452ms.
13:33:24 [build] Building static entrypoints...
13:33:25 [WARN] [vite] 
/blog-light.svg referenced in /blog-light.svg didn't resolve at build time, it will remain unchanged to be resolved at runtime
13:33:25 [WARN] [vite] 
/blog.svg referenced in /blog.svg didn't resolve at build time, it will remain unchanged to be resolved at runtime
13:33:25 [vite] ✓ built in 506ms
13:33:25 [build] ✓ Completed in 509ms.

 building client (vite) 
13:33:25 [vite] ✓ 22 modules transformed.
13:33:25 [vite] dist/build/q-bundle-graph-4i42i.json   0.19 kB │ gzip:  0.16 kB
13:33:25 [vite] dist/q-manifest.json                   2.20 kB │ gzip:  0.67 kB
13:33:25 [vite] dist/qwik-prefetch-service-worker.js   3.66 kB
13:33:25 [vite] dist/_astro/page.C89vApUe.js           0.04 kB │ gzip:  0.06 kB
13:33:25 [vite] dist/_astro/hoisted.N60B7c6T.js        0.16 kB │ gzip:  0.15 kB
13:33:25 [vite] dist/_astro/navButton.D5IKX5LY.js      0.52 kB │ gzip:  0.38 kB
13:33:25 [vite] dist/_astro/index.BG2nPUTX.js          2.20 kB │ gzip:  0.98 kB
13:33:25 [vite] dist/_astro/theme.DkXSPouq.js          3.78 kB │ gzip:  0.96 kB
13:33:25 [vite] dist/_astro/nav.Dkf5uWmU.js            7.03 kB │ gzip:  1.90 kB
13:33:25 [vite] dist/_astro/hoisted.C1PoabJt.js       12.03 kB │ gzip:  4.17 kB
13:33:25 [vite] dist/_astro/core.prod.BsIg0y2v.js     60.21 kB │ gzip: 21.98 kB
13:33:25 [vite] ✓ built in 135ms

 generating static routes 
13:33:25 ▶ src/pages/blog.astro
13:33:25   └─ /blog/index.htmlMissing client manifest, loading symbols in the client might 404. Please ensure the client build has run and generated the manifest for the server build.
Missing client manifest, loading symbols in the client might 404. Please ensure the client build has run and generated the manifest for the server build.
serializeQRL: Cannot resolve symbol s_IDRPwPZ2wZ8 in null undefined
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_IDRPwPZ2wZ8 Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
    at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3362:11)
    at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3099:16)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:819:52)
    at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:631:19)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:917:22)
    at reduce (:1:11)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:836:21)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:586:16)
    at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:584:29)
    at processTicksAndRejections (:12:39)
serializeQRL: Cannot resolve symbol s_ArvH2YmMldY in null undefined
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_ArvH2YmMldY Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
    at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3362:11)
    at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3099:16)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:819:52)
    at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:631:19)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:917:22)
    at reduce (:1:11)
    at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:836:21)
    at <anonymous> (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:586:16)
    at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:584:29)
    at processTicksAndRejections (:12:39)
Error in renderToStaticMarkup function of @qwikdev/astro:  31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                            ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3097:7)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:2652:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:13:19
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4443:8)

Error in renderToStaticMarkup function of @qwikdev/astro:  31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                            ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3097:7)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:2652:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:13:19
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4443:8)

31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                            ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3097:7)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:2652:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:13:19
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4443:8)
31 | const logErrorAndStop = (message, ...optionalParams) => createAndLogError(true, message, ...optionalParams);
32 | const logWarn = () => {
33 | };
34 | const printParams = (optionalParams) => optionalParams;
35 | const createAndLogError = (asyncThrow, message, ...optionalParams) => {
36 |   const err = message instanceof Error ? message : new Error(message);
                                                            ^
error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
      at createAndLogError (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:36:56)
      at serializeQRL (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:3097:7)
      at mapJoin (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:2652:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4748:47)
      at renderNodeVirtual (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4516:19)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:13:19
      at reduce (:1:11)
      at renderNode (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4770:10)
      at /home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4445:10
      at renderRoot$1 (/home/nathan/Projects/bunsonalWebsite/dist/chunks/server_Chl5L0Ae.mjs:4443:8)

Bun v1.1.20 (Linux x64)
```

**Comment by nduartech** [comment]
I am also using
include: '**/qwik/*',
though I am not using a Qwik library outside of the base site

**Comment by siguici** [comment]
@nduartech,  I just checked your code. The error comes from Bun. You should use `bun` (just like that) instead of `bunx --bun`.
I'll make a PR that fixes some things.

**Comment by siguici** [comment]
You can see the fixes in the PR https://github.com/nduartech/bunsonalWebsite/pull/2
