### ISSUE TITLE
[🐛] Qwik DOM testing package currently coupled to Qwik Router

### ISSUE THREAD

**Issue by yoroshikun** [QwikDev/astro#31]
First thanks for working on this integration, it is super interesting to play with the integration of multi awesome concepts for making the web faster and better.
Please let me know if this is not related at all to this integration, throughout troubleshooting it seems to only affect astro template so far.

I am trying to setup Vitest with it to enable some unit testing.

I have attempted to setup Vitest with the following steps that are outlined in a blog [here](https://www.thisdot.co/blog/unit-testing-qwik-components) It however uses qwik city and vite instead.

1. Install vitest with `npm i vitest --save-dev`
2. Create a `vitest.config.ts` with the following
```ts
/// <reference types="vitest" />
import { getViteConfig } from 'astro/config';

export default getViteConfig({
	test: {
    exclude: ['~', 'node_modules', 'dist', 'public'],
	},
});
```
3. Add the Counter.tsx (small change to have count in a div and class count for test targeting) (from README.md example) and a Counter.test.tsx with the following content for basic test
```tsx
import { createDOM } from '@builder.io/qwik/testing'; // import the createDOM method
import { describe, expect, it } from 'vitest';
import Counter from './Counter';

describe('Counter component', function () {
  it('should render', async () => {
    // create the component's DOM and get back the container and a render method
    const { screen, render } = await createDOM();

    // call the render method with the JSX node of our Counter component as a parameter
    await render(<Counter />);

    // get the div that displays the count from our container
    const countElement = screen.querySelector('.count');

    // assert the displayed count is "0" which is the default value
    expect(countElement?.textContent).toBe('0');
  });
});
```

**Expected outcome:** (from the qwik city example)
```
✓ src/components/starter/counter/counter.test.tsx (1)
   ✓ Counter component (1)
     ✓ should render

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  19:11:43
   Duration  617ms (transform 367ms, setup 0ms, collect 405ms, tests 27ms, environment 0ms, prepare 48ms)


  ❗️ Expect significant performance loss in development.
  ❗️ Disabling the browser's cache results in waterfall requests.
```
Also as a bonus does anyone know why it has these warnings for performance?

**Actual Outcome:**
```
 FAIL  src/components/Counter/Counter.test.tsx [ src/components/Counter/Counter.test.tsx ]
Error: Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.
 ❯ $ dist-dev/tsc-out/packages/qwik/src/core/qrl/qrl.public.js:83:15
 ❯ Module.component$ dist-dev/tsc-out/packages/qwik/src/core/component/component.public.js:140:25
 ❯ src/components/Counter/Counter.tsx:4:16
      2| import styles from './counter.module.css';
      3| 
      4| export default component$(() => {
       |                ^
      5|   const count = useSignal(70);
      6| 
 ❯ src/components/Counter/Counter.test.tsx:4:31

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  19:35:12
   Duration  239ms (transform 24ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 40ms)
```

Any information on this would be awesome, I struggled finding any information on this through some searches. 🙇 

**Extra**
When trying to build it happens to do this as well
```
✓ built in 663ms
"fileURLToPath" is not exported by "__vite-browser-external", imported by "node_modules/@builder.io/qwik/testing/index.mjs".
file: /Users/me/projects/personal/site/node_modules/@builder.io/qwik/testing/index.mjs:22378:9
22376: // packages/qwik/src/testing/platform.ts
22377: import { existsSync } from "fs";
22378: import { fileURLToPath } from "url";
```

**Comment by thejackshelton** [comment]
>  ❗️ Expect significant performance loss in development.
  ❗️ Disabling the browser's cache results in waterfall requests.

It's because the service worker is disabled in dev mode (and speculative module fetching)
https://qwik.builder.io/docs/advanced/speculative-module-fetching/#speculative-module-fetching

This makes sure dev mode is never stale.

> I have attempted to setup Vitest with the following steps that are outlined in a blog [here](https://www.thisdot.co/blog/unit-testing-qwik-components) It however uses qwik city and vite instead.

Yeah this blog post came out when Qwik City was the only meta-framework option for Qwik.

I would follow Astro's vitest guide and example:
https://docs.astro.build/en/guides/testing/#vitest
https://github.com/withastro/astro/tree/latest/examples/with-vitest/test

Qwik City is an alternative to Astro. It's similar to what Next.js is to React for example. They are incompatible.

**Comment by yoroshikun** [comment]
@thejackshelton I actually did follow those two links you provided and did not have any luck. Let me create a reproduction.

The astro vitest does not have DOM tests, and the testing documentation is very barebones on if it is actually working or not.

Pleas check this reproduction, [Here](https://codesandbox.io/p/sandbox/github/withastro/astro/tree/latest/examples/with-vitest?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp6488xc00083b6e8ote8o9l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp6488xc00033b6e89v5gis2%2522%253A%257B%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%252C%2522activeTabId%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00023b6e9drkrmbe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp648z2b004q3b6eehrhfn45%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.spec.tsx%2522%252C%2522id%2522%253A%2522clp64bv9100kx3b6exwvsmz0l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522id%2522%253A%2522clp64ciiy00q83b6e6x63u5nj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.tsx%2522%252C%2522id%2522%253A%2522clp64ekx900xr3b6eboaeztwx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.astro%2522%252C%2522id%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp6488xc00073b6eceksn61y%2522%253A%257B%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%252C%2522activeTabId%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00063b6etyqjwx0v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clp64j09j01wq3b6eu8m2gv0a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clp6488xc00053b6e2w433y5o%2522%253A%257B%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%252C%2522activeTabId%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00043b6eat5jn0qb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp649gvt000aegem06nhb4s1%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Running test will fail for DOM and running build will also fail with lots of warnings and error at end.

**Comment by thejackshelton** [comment]
> @thejackshelton I actually did follow those two links you provided and did not have any luck. Let me create a reproduction.
> 
> The astro vitest does not have DOM tests, and the testing documentation is very barebones on if it is actually working or not.
> 
> Pleas check this reproduction, [Here](https://codesandbox.io/p/sandbox/github/withastro/astro/tree/latest/examples/with-vitest?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp6488xc00083b6e8ote8o9l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp6488xc00033b6e89v5gis2%2522%253A%257B%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%252C%2522activeTabId%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00023b6e9drkrmbe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp648z2b004q3b6eehrhfn45%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.spec.tsx%2522%252C%2522id%2522%253A%2522clp64bv9100kx3b6exwvsmz0l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522id%2522%253A%2522clp64ciiy00q83b6e6x63u5nj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.tsx%2522%252C%2522id%2522%253A%2522clp64ekx900xr3b6eboaeztwx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.astro%2522%252C%2522id%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp6488xc00073b6eceksn61y%2522%253A%257B%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%252C%2522activeTabId%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00063b6etyqjwx0v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clp64j09j01wq3b6eu8m2gv0a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clp6488xc00053b6e2w433y5o%2522%253A%257B%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%252C%2522activeTabId%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00043b6eat5jn0qb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp649gvt000aegem06nhb4s1%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
> 
> Running test will fail for DOM and running build will also fail with lots of warnings and error at end.

I'm a bit confused, does it work without the `@qwikdev/astro` integration, and then when it's added it doesn't work?

**Comment by yoroshikun** [comment]
Sorry for some reason the link was just the template not the repro, [Here](https://codesandbox.io/p/devbox/astro-qwik-vitest-dom-issue-mjyzlw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp6488xc00083b6e8ote8o9l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp6488xc00033b6e89v5gis2%2522%253A%257B%2522id%2522%253A%2522clp6488xc00033b6e89v5gis2%2522%252C%2522activeTabId%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00023b6e9drkrmbe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp648z2b004q3b6eehrhfn45%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.spec.tsx%2522%252C%2522id%2522%253A%2522clp64bv9100kx3b6exwvsmz0l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522id%2522%253A%2522clp64ciiy00q83b6e6x63u5nj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCounter.tsx%2522%252C%2522id%2522%253A%2522clp64ekx900xr3b6eboaeztwx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.astro%2522%252C%2522id%2522%253A%2522clp64j9lq01yd3b6eezrjyplo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp6488xc00073b6eceksn61y%2522%253A%257B%2522id%2522%253A%2522clp6488xc00073b6eceksn61y%2522%252C%2522activeTabId%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00063b6etyqjwx0v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4321%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clp64j09j01wq3b6eu8m2gv0a%2522%252C%2522mode%2522a%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clp64legr02hf3b6eeoyi2qwp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clp6488xc00053b6e2w433y5o%2522%253A%257B%2522id%2522%253A%2522clp6488xc00053b6e2w433y5o%2522%252C%2522activeTabId%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp6488xc00043b6eat5jn0qb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp649gra00e53b6ejlo0hq39%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp649gvt000aegem06nhb4s1%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is the repo 🙇

**Comment by thejackshelton** [comment]
Hey will try to figure out what to do here, but it looks like that can't be achieved without externally touching the @builder.io/qwik/esting package, and figuring out how to extract out the qwikCity plugin from the package.

**Comment by winnietthepooh** [comment]
I am also running into the same problem in this [repo](https://github.com/winnietthepooh/qwik-astro-test). Brand new template did the same steps as shown in the [video](https://www.youtube.com/watch?v=LIKxkSzHqeo) where Steve announced it a month ago. Only differences that may be affecting it is using Astro 4.0. Getting this output 
`[ERROR] Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.` 
when using the verbose flag I get this full stack trace `[ERROR] Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.
  Stack trace:
    at $ (file:///C:/Users/crx2s/Desktop/projects/qwik-astro-test/node_modules/@builder.io/qwik/core.mjs:8581:15)
    at C:\Windows_Path\qwik-astro-test\components\counter.tsx:3:24`
the stack trace points to `component$` in counter.tsx

**Comment by thejackshelton** [comment]
> I am also running into the same problem in this [repo](https://github.com/winnietthepooh/qwik-astro-test). Brand new template did the same steps as shown in the [video](https://www.youtube.com/watch?v=LIKxkSzHqeo) where Steve announced it a month ago. Only differences that may be affecting it is using Astro 4.0. Getting this output `[ERROR] Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.` when using the verbose flag I get this full stack trace `[ERROR] Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead. Stack trace: at $ (file:///C:/Users/crx2s/Desktop/projects/qwik-astro-test/node_modules/@builder.io/qwik/core.mjs:8581:15) at C:\Windows_Path\qwik-astro-test\components\counter.tsx:3:24` the stack trace points to `component$` in counter.tsx

Yeah I'm gonna try to tackle this next, although I think the challenging part is this seems to be something tied to Qwik City 😬 .

Will see if there's an astro way of doing this first and then circle back to what we can do there.

**Comment by thejackshelton-kunaico** [comment]
Hey y'all! I know this issue has been up for ages (the longest in this integration)

This package is intended for the Qwik core team, instead please use https://github.com/ianlet/qwik-testing-library

**Comment by thejackshelton** [comment]
Hey y'all! I know this issue has been up for ages (the longest in this integration)

This package is intended for the Qwik core team, instead please use https://github.com/ianlet/qwik-testing-library
