### ISSUE TITLE
Compiler Errors with multiple lines imports

### ISSUE THREAD

**Issue by fabiobiondi** [QwikDev/astro#7]
Hi,
 
I have noticed that everything is working fine if I use inline imports like the following:

```ts
import { component$, useSignal } from "@builder.io/qwik";
```

while I receive the "Error: Code(31)" if I use multiple lines (especially if the "import" keyword and '@builder.io/* ' are in different lines:

```ts
import { 
component$, useSignal
} from "@builder.io/qwik";
```

Error log:
```

QWIK ERROR Error: Code(31)
    at createAndLogError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:50:54)
    at logErrorAndStop (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:42:57)
    at qError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:59:12)
    at serializeQRL (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3725:15)
    at file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:42
    at mapJoin (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3428:20)
    at serializeQRLs (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:12)
    at renderNode (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:1957:60)
    at processData (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2013:24)
    at walkChildren (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2044:16) s_Nx3K86jjfOI
Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31)
    at createAndLogError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:50:54)
    at logErrorAndStop (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:42:57)
    at qError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:59:12)
    at serializeQRL (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3725:15)
    at file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:42
    at mapJoin (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3428:20)
    at serializeQRLs (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:12)
    at renderNode (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:1957:60)
    at processData (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2013:24)
    at walkChildren (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2044:16)
Error in check function of @qwikdev/astro:  Error: Code(31)
    at createAndLogError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:50:54)
    at logErrorAndStop (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:42:57)
    at qError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:59:12)
    at serializeQRL (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3725:15)
    at file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:42
    at mapJoin (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3428:20)
    at serializeQRLs (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:12)
    at renderNode (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:1957:60)
    at processData (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2013:24)
    at walkChildren (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2044:16)
file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:53
        throw err;
        ^

Error: Code(31)
    at createAndLogError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:50:54)
    at logErrorAndStop (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:42:57)
    at qError (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:59:12)
    at serializeQRL (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3725:15)
    at file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:42
    at mapJoin (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3428:20)
    at serializeQRLs (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:3740:12)
    at renderNode (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:1957:60)
    at processData (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2013:24)
    at walkChildren (file:///Users/fabiobiondi/Desktop/training/astro-qwik-integration-demo/dist/chunks/pages/index_957913fa.mjs:2044:16)
```

## UPDATE
My friend @gabdisi already made a PR to fix the issue ♥️

**Comment by thejackshelton** [comment]
y'all rock 🎸 ! releasing a new version.

**Comment by thejackshelton** [comment]
Closing for now, but I'm gonna keep a note of the AST approach that @gabdisi mentioned.
